// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://towaahsltwaigixiecof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvd2FhaHNsdHdhaWdpeGllY29mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0ODE4MDYsImV4cCI6MjA1MzA1NzgwNn0.cAhzf75756K989mCe7wBmVTENupGEFw88-x9ZVXl3D4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);